Repository dsathe/noteassistant, pull requests merged in 2024-12, with the labels that each got.

#6 Fetching Notes from database to dashboard page
  package-lock.json
  package.json
  src/app/dashboard/page.tsx
Labels: enhancement

#8 Added toast messages for note creation
  README.md
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/CreateNoteDialog.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/hooks/use-toast.ts
Labels: ui

#7 Adding masonry layout changes
  src/app/dashboard/page.tsx
  src/components/NoteCard.tsx
Labels: ui

#9 Adding notecolor to Notes
  prisma/schema.prisma
  src/app/api/createNoteBook/route.ts
  src/app/dashboard/page.tsx
  src/components/CreateNoteDialog.tsx
  src/components/NoteCard.tsx
Labels: ui

#10 Added cover image to the notes
  env.example
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/createNoteBook/route.ts
  src/app/api/saveNote/route.ts
  src/app/api/updateCoverImage/route.ts
  src/app/api/uploadthing/core.ts
  src/app/api/uploadthing/route.ts
  src/app/dashboard/page.tsx
  src/app/notebook/[noteId]/page.tsx
  src/components/CoverImageModal.tsx
  src/components/CreateNoteDialog.tsx
  src/components/EditorClient.tsx
  src/lib/services/note-service.ts
  src/lib/services/user-service.ts
  src/lib/validation/note.ts
  src/utils/uploadthing.ts
  tailwind.config.ts
Labels: documentation, enhancement, ui

#12 feat: added delete functionality
  src/app/api/deleteNote/route.ts
  src/app/api/saveNote/route.ts
  src/app/dashboard/page.tsx
  src/components/DeleteButton.tsx
  src/components/EditorClient.tsx
  src/components/NoteCard.tsx
  src/lib/services/note-service.ts
Labels: documentation, enhancement, ui

#13 Editor upgrade
  next.config.ts
  package-lock.json
  package.json
  public/icons/add-column-svg.svg
  public/icons/add-row-svg.svg
  public/icons/delete-column-svg.svg
  public/icons/delete-row-svg.svg
  public/icons/table-delete-svg.svg
  src/app/globals.css
  src/components/TipTapEditor.tsx
  src/components/TipTapMenuBar.tsx
Labels: enhancement, ui

#14 AutoComplete and Saving Shortcut
  env.example
  package-lock.json
  package.json
  src/app/api/completion/route.ts
  src/components/TipTapEditor.tsx
Labels: enhancement, ui
