Repository dsathe/noteassistant, pull requests merged in 2025-01, with the labels that each got.

#15 Integrated a AI Chatbot to the Dashboard
  env.example
  next.config.ts
  package-lock.json
  package.json
  src/app/api/chatbot/route.ts
  src/app/api/deleteNote/route.ts
  src/app/api/saveNote/route.ts
  src/app/dashboard/page.tsx
  src/components/AIChatBot.tsx
  src/components/ChatBox.tsx
  src/components/ui/textarea.tsx
  src/lib/db/pinecone.ts
  src/lib/huggingface.ts
  src/lib/services/note-service.ts
Labels: enhancement

#16 feat: added favorites
  package-lock.json
  prisma/schema.prisma
  src/app/api/toggleFavorite/route.ts
  src/app/dashboard/page.tsx
  src/components/ChatBox.tsx
  src/components/DisplayNotes.tsx
  src/components/EditorClient.tsx
  src/components/FavoritesButton.tsx
  src/components/NoteCard.tsx
  src/lib/services/note-service.ts
Labels: enhancement, ui

#17 Cover image Generation using AI
  src/app/api/chatbot/route.ts
  src/app/api/imageGeneration/route.ts
  src/components/CoverImageModal.tsx
  src/lib/huggingface.ts
Labels: enhancement, AI

#18 Adding search bar and searching functionality
  package-lock.json
  package.json
  src/app/api/chatbot/route.ts
  src/app/api/completion/route.ts
  src/app/api/toggleFavorite/route.ts
  src/app/dashboard/page.tsx
  src/app/layout.tsx
  src/components/DisplayNotes.tsx
  src/components/NavbarComponents.tsx
  src/components/SearchBar.tsx
  src/lib/huggingface.ts
  src/stores/searchstore.ts
Labels: enhancement, ui

#19 Made the ui responsive
  src/app/api/uploadthing/core.ts
  src/components/AIChatBot.tsx
  src/components/ChatBox.tsx
  src/components/CreateNoteDialog.tsx
  src/components/DisplayNotes.tsx
  src/components/EditorClient.tsx
  src/components/NavbarComponents.tsx
  src/components/NoteCard.tsx
  src/components/SearchBar.tsx
  src/components/TipTapEditor.tsx
Labels: ui

#20 Adding changes to README
  README.md
  Screenshots/Chatbot.png
  Screenshots/CodeBlock.png
  Screenshots/CoverImage1.png
  Screenshots/CoverImage2.png
  Screenshots/CreateNotes.png
  Screenshots/Dashboard.png
  Screenshots/Responsive1.png
  Screenshots/Responsive2.png
Labels: documentation
